import type { User, Lead, CalendarEvent, ChatMessage } from "@/types/types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Admin User",
    email: "admin@validiz.com",
    role: "admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "John BD",
    email: "john@validiz.com",
    role: "bd",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Jane Developer",
    email: "jane@validiz.com",
    role: "developer",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Mike Developer",
    email: "mike@validiz.com",
    role: "developer",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

export const mockLeads: Lead[] = [
  {
    id: "1",
    clientName: "TechCorp Inc",
    jobDescription: "Senior React Developer position for a fintech startup",
    source: "linkedin",
    status: "new",
    assignedDeveloperId: "3",
    assignedDeveloper: mockUsers[2],
    createdById: "2",
    createdBy: mockUsers[1],
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
    attachments: [],
    notes: [],
    history: [],
  },
  {
    id: "2",
    clientName: "StartupXYZ",
    jobDescription: "Full-stack developer with Node.js and React experience",
    source: "website",
    status: "interview_scheduled",
    assignedDeveloperId: "4",
    assignedDeveloper: mockUsers[3],
    createdById: "2",
    createdBy: mockUsers[1],
    createdAt: "2024-01-14T14:30:00Z",
    updatedAt: "2024-01-16T09:15:00Z",
    attachments: [],
    notes: [],
    history: [],
  },
  {
    id: "3",
    clientName: "Enterprise Solutions",
    jobDescription:
      "Backend developer specializing in microservices architecture",
    source: "referral",
    status: "test_assigned",
    assignedDeveloperId: "3",
    assignedDeveloper: mockUsers[2],
    createdById: "1",
    createdBy: mockUsers[0],
    createdAt: "2024-01-10T16:45:00Z",
    updatedAt: "2024-01-18T11:20:00Z",
    attachments: [],
    notes: [],
    history: [],
  },
];

export const mockEvents: CalendarEvent[] = [
  {
    id: "1",
    title: "Interview with TechCorp",
    description: "Technical interview for React Developer position",
    startTime: "2024-02-01T14:00:00Z",
    endTime: "2024-02-01T15:00:00Z",
    leadId: "1",
    lead: mockLeads[0],
    developerId: "3",
    developer: mockUsers[2],
    createdById: "2",
    createdBy: mockUsers[1],
    type: "interview",
  },
  {
    id: "2",
    title: "Coding Test Review",
    description: "Review coding test submission",
    startTime: "2024-02-02T10:00:00Z",
    endTime: "2024-02-02T11:00:00Z",
    leadId: "3",
    lead: mockLeads[2],
    developerId: "3",
    developer: mockUsers[2],
    createdById: "1",
    createdBy: mockUsers[0],
    type: "test",
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: "1",
    leadId: "1",
    message: "Initial contact made with the client. They seem very interested.",
    userId: "2",
    user: mockUsers[1],
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    leadId: "1",
    message:
      "I've reviewed the job requirements. This looks like a good fit for my skills.",
    userId: "3",
    user: mockUsers[2],
    createdAt: "2024-01-15T11:15:00Z",
  },
];
